name : genMatrix CI

on:
  push:
    branches: main
    
  pull_request:
    branches: main

jobs:
  build-test:
    runs-on: ubuntu-slim

    steps:
      - name : Checkout
        uses : actions/checkout@v4
        with : 
          submodules: recursive
      
      - name : Dependencies
        run  : "sudo apt-get update && sudo apt-get install -y cmake g++ make"

      - name : Build
        run  : make test_build

      - name : Run
        run  : ./build/genMatrix_gtest --gtest_color=yes
